Repository hiroaki514/contents_management_app, pull requests merged in 2023-06, with the labels that each got.

#118 seedファイルとSystemSpecを修正
  app/views/layouts/_header.html.erb
  bin/rails
  bin/rake
  bin/setup
  db/fixtures/development/01_user.rb
  spec/system/users_spec.rb
Labels: バグ修正

#117 Rubocop.ymlファイルを修正
  .rubocop.yml
  db/fixtures/development/01_user.rb
  db/fixtures/test/01_user.rb
Labels: その他

#135 Postモデルの追加とアソシエーション追加
  README.md
  app/models/post.rb
  app/models/user.rb
  db/migrate/20230630112713_create_posts.rb
  db/schema.rb
  spec/factories/posts.rb
  spec/models/post_spec.rb
  spec/system/users_spec.rb
Labels: メンタリングでの作成
