Repository hiroaki514/contents_management_app, pull requests merged in 2023-05, with the labels that each got.

#102 コンテナが起動しない問題の修正
  README.md
  docker-compose.yml
Labels: その他

#98 MySQL8.0.32にアップグレードする
  docker-compose.yml
Labels: サーバ側

#100 【記述例】エラーメッセージを検証するRSpec
  spec/models/user_spec.rb
Labels: サーバ側

#96 ページネーションのデザイン変更
  Gemfile
  Gemfile.lock
  app/controllers/admin_controller.rb
  app/views/admin/index.html.erb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/master/index.html.erb
Labels: Issues

#105 rubyのversionを3.2.1から3.2.2へ変更
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: サーバ側

#111 SimpleCovのgemを追加
  .gitignore
  Gemfile
  Gemfile.lock
  db/schema.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
Labels: gem追加

#90 ヘッダーのひな型追加
  app/controllers/master_controller.rb
  app/views/admin/index.html.erb
  app/views/general/index.html.erb
  app/views/layouts/_admin_side_bar.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/_master_side_bar.html.erb
  app/views/master/index.html.erb
Labels: その他

#116 seed_fuのユーザデータを更新、伴いページネーション表示数変更
  app/controllers/admin_controller.rb
  app/controllers/master_controller.rb
  app/views/admin/index.html.erb
  app/views/master/index.html.erb
  db/fixtures/development/01_user.rb
  db/fixtures/test/01_user.rb
Labels: その他
