Repository hiroaki514/contents_management_app, pull requests merged in 2023-04, with the labels that each got.

#69 Capybaraを導入し統合テストを実行できる環境を整える
  Dockerfile
  spec/rails_helper.rb
  spec/support/capybara.rb
Labels: サーバ側

#73 gitignoreファイルに追記
  .gitignore
  bin/rails
  bin/rake
  bin/setup
Labels: その他

#74 0401
  spec/system/users_spec.rb
Labels: メンタリングでの作成

#80 shoulda matchersを追加
  Gemfile
  Gemfile.lock
Labels: Issues

#79 dependabotで毎週月曜日午前8時にプルリクを作成するよう変更
  .github/dependabot.yml
Labels: Issues

#78 アイコン画像アップロード時のバリデーション追加
  README.md
  app/controllers/master_controller.rb
  app/models/user.rb
Labels: メンタリングでの作成

#88 0415_kaminari
  Gemfile
  Gemfile.lock
  app/controllers/master_controller.rb
  app/views/master/index.html.erb
  app/views/master/show.html.erb
  config/initializers/kaminari_config.rb
Labels: メンタリングでの作成

#92 ユーザ一覧を表示
  README.md
  app/controllers/admin_controller.rb
  app/views/admin/index.html.erb
  app/views/master/index.html.erb
Labels: メンタリングでの作成
